export let enchMap = new Map<string,string>();
export let levelMap = new Map<string,number>();
export let unusualItem = ["invisibleBedrock","invisiblebedrock","bedrock","mob_spawner","spawn_egg","command_block","dragon_egg","end_portal_frame","beacon"];
enchMap.set("0","protection");
enchMap.set("1","fire_aspect");
enchMap.set("2","feather_falling");
enchMap.set("3","blast_protection");
enchMap.set("4","projectile_protection");
enchMap.set("5","thorns");

enchMap.set("6","respiration");
enchMap.set("7","depth_strider");
enchMap.set("8","aqua_affinity");
enchMap.set("9","sharpness");
enchMap.set("10","smite");
enchMap.set("11","bane_of_arthropods");

enchMap.set("12","knockback");
enchMap.set("13","fire_aspect");
enchMap.set("14","looting");
enchMap.set("15","efficiency");
enchMap.set("16","silk_touch");
enchMap.set("17","unbreaking");

enchMap.set("18","fortune");
enchMap.set("19","power");
enchMap.set("20","punch");
enchMap.set("21","flame");
enchMap.set("22","infinity");
enchMap.set("23","luck_of_the_sea");

enchMap.set("24","lure");
enchMap.set("25","frost_walker");
enchMap.set("26","mending");
enchMap.set("27","");
enchMap.set("28","");
enchMap.set("29","impaling");

enchMap.set("30","riptide");
enchMap.set("31","loyalty");
enchMap.set("32","channeling");

levelMap.set("0",4);
levelMap.set("1",4);
levelMap.set("2",4);
levelMap.set("3",4);
levelMap.set("4",4);
levelMap.set("5",3);
levelMap.set("6",3);
levelMap.set("7",3);
levelMap.set("8",1);
levelMap.set("9",5);
levelMap.set("10",5);
levelMap.set("11",5);
levelMap.set("12",2);
levelMap.set("13",2);
levelMap.set("14",3);
levelMap.set("15",5);
levelMap.set("16",1);
levelMap.set("17",3);
levelMap.set("18",3);
levelMap.set("19",5);
levelMap.set("20",2);
levelMap.set("21",1);
levelMap.set("22",1);
levelMap.set("23",3);
levelMap.set("24",3);
levelMap.set("25",2);
levelMap.set("26",1);
levelMap.set("27",1);
levelMap.set("28",1);
levelMap.set("29",5);
levelMap.set("30",3);
levelMap.set("31",3);
levelMap.set("32",1);
levelMap.set("33",1);
levelMap.set("34",4);
levelMap.set("35",3);